export {
  Close as CloseIcon,
  Search as SearchIcon,
  CheckCircle as CheckCircleIcon,

  //Outlined Icons
  DashboardOutlined as DashboardIcon,
  BusinessOutlined as OrganizationIcon,
  GroupOutlined as UsersIcon,
  AccountBalanceOutlined as BankIcon,
  CategoryOutlined as CategoryIcon,
  StoreOutlined as MpcsIcon,
  ShoppingCartOutlined as SalesIcon,
  ReceiptLongOutlined as InvoiceIcon,
  DescriptionOutlined as DocumentsIcon,
  LocalShippingOutlined as TruckIcon,
  Inventory2Outlined as ProductIcon,
  SellOutlined as PricingIcon,
  AdminPanelSettingsOutlined as AdminPanelIcon,
  PersonOutlined as UserIcon,
  LockOutlined as LockIcon,
  VisibilityOutlined as VisibilityOutlinedIcon,
  VisibilityOffOutlined as VisibilityOffOutlinedIcon,

  // Rounded Icons
  VerifiedUserRounded as ShieldIcon,
  ArrowBackRounded as ArrowBackIcon,
  ArrowForwardRounded as ArrowForwardIcon,
  LanguageRounded as GlobalIcon,
  SettingsRounded as SettingsIcon,
  LogoutRounded as LogoutIcon,
  PersonRounded as PersonIcon,
  MailRounded as MailIcon,
  SecurityRounded as SecurityIcon,
  NotificationsRounded as NotificationsIcon,
  SwapHorizRounded as SwapHorizIcon,
  SegmentRounded as SegmentIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  DeleteForeverRounded as DeleteIcon,
  SaveRounded as SaveIcon,
  CancelRounded as CancelIcon,

  // Action & Table Icons (Rounded)
  AddRounded as AddIcon,
  EditRounded as EditIcon,
  PlayArrowRounded as PlayArrowIcon,
  ContentCopyRounded as CopyIcon,
  DownloadRounded as DownloadIcon,
  PrintRounded as PrintIcon,
  VisibilityRounded as VisibilityIcon,
  VisibilityOffRounded as VisibilityOffIcon,
  NavigateNextRounded as NavigateNextIcon,
  SearchOffRounded as SearchOffIcon,
  HistoryRounded as HistoryIcon,
  CalendarTodayRounded as CalendarTodayIcon,
  ArrowUpward as ArrowUpIcon,
  ArrowDownward as ArrowDownIcon,
} from "@mui/icons-material";

export * from "./MilkCanIcon";
